### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by gauravkulkarni96** [codyparker/channels-obstruction#1]
Hi
I was trying to run the application and I'm facing this issue. It just shows lets play at /lobby after login. 
![screenshot at 2017-03-28 19 01 38](https://cloud.githubusercontent.com/assets/12571941/24408000/11f3d048-13ea-11e7-9df1-2e930c6cf617.png)

How do I get it to work?
Thanx

**Comment by codyparker** [comment]
Hello,

Do you see any errors in your runserver terminal or in the browser console? Also, did you clone this repository or are you working on the tutorial in the blog post?

**Comment by gauravkulkarni96** [comment]
Nope, there are no errors in the runserver.
I've cloned this repository.

**Comment by codyparker** [comment]
I've just tested cloning it fresh and going through the steps I listed and it worked for me. I did forget one step and just added it to the project description, which is to run `webpack` to build the JS packages. But I would think you would have received a Django template error.


Did you run `webpack` in your terminal? 
Also, are there any errors in your browser console to give us a clue?

**Comment by gauravkulkarni96** [comment]
yes I did run webpack
Yes, Theres this error in the console `http://localhost:8080/current-user/?format=json Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by codyparker** [comment]
Are you running the server on port 8080? I believe the React components may be hard-coded to call out on that port in this example project.

If you are on port 8080, what happens when you try to hit the error's URL directly?

**Comment by gauravkulkarni96** [comment]
Oh.. I wasn't running it on 8080. But when I did now, I'm getting this in the console : `XMLHttpRequest cannot load http://localhost:8080/current-user/?format=json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.`

This is what I get if I directly go to the error URL `{"id":null,"username":"","groups":[]}`

**Comment by codyparker** [comment]
OK, thanks. I've updated the project instructions to include running on port 8080. The blog post that walks you through the project uses that port, but I just didn't make it dynamic in the example project. I may update that soon so that any port works.

Now, the error you're getting is probably because your browser is using http://127.0.0.1:8080 and trying to communicate to http://localhost:8080 as the backend. It thinks you're attempting to connect to a different domain. Make sure the browser is also using localhost:8080 and you should be good-to-go.

**Comment by gauravkulkarni96** [comment]
Yes It worked!!
Thankyou so much! I was struggling on this from past 2 days.
By the way the tutorial is just awesome. Thankyou for that.

**Comment by codyparker** [comment]
Thanks! I appreciate the feedback! Glad you got it working, too.
