### ISSUE TITLE
Wepack error

### ISSUE THREAD

**Issue by RafayelGardishyan** [codyparker/channels-obstruction#6]
When I try to run webpack with --config webpack.config.js I recieve this error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by codyparker** [comment]
I can't recreate that issue, but it the error seems to indicate that the `extensions` setting under `resolve` in the webpack.config.js file could be empty. Have you modified the config file? If not, it could be a webpack version issue.

I did just realize that my instructions used the globally installed webpack, which could cause issues with having different versions installed. I modified `package.json` to include an "npm run" script for the local project webpack. 

Try getting the latest package.json and then run `npm run webpack` to see if that works.
